config/routes.rb
Rails.application.routes.draw do
    namespace :api, defaults: {format: :json} do  
      resources :wines
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "static_pages#root"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wine.rb
class Wine < ApplicationRecord
end

app/controllers/api/wines_controller.rb
class Api::WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:id, :winery_full, :wine_full, :vintage, :note, :taster_initials, :color, :country, :region, :score, :price, :issue_date, :top_100_year, :top100_rank)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/root.html.erb
  <script type="text/javascript">
    
  </script>

<main id="root"></main>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :winery_full %>
    <%= form.text_field :winery_full %>
  </div>

  <div class="field">
    <%= form.label :wine_full %>
    <%= form.text_field :wine_full %>
  </div>

  <div class="field">
    <%= form.label :vintage %>
    <%= form.number_field :vintage %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :taster_initials %>
    <%= form.text_field :taster_initials %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :issue_date %>
    <%= form.date_select :issue_date %>
  </div>

  <div class="field">
    <%= form.label :top_100_year %>
    <%= form.number_field :top_100_year %>
  </div>

  <div class="field">
    <%= form.label :top100_rank %>
    <%= form.number_field :top100_rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Winery full</th>
      <th>Wine full</th>
      <th>Vintage</th>
      <th>Note</th>
      <th>Taster initials</th>
      <th>Color</th>
      <th>Country</th>
      <th>Region</th>
      <th>Score</th>
      <th>Price</th>
      <th>Issue date</th>
      <th>Top 100 year</th>
      <th>Top100 rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.id %></td>
        <td><%= wine.winery_full %></td>
        <td><%= wine.wine_full %></td>
        <td><%= wine.vintage %></td>
        <td><%= wine.note %></td>
        <td><%= wine.taster_initials %></td>
        <td><%= wine.color %></td>
        <td><%= wine.country %></td>
        <td><%= wine.region %></td>
        <td><%= wine.score %></td>
        <td><%= wine.price %></td>
        <td><%= wine.issue_date %></td>
        <td><%= wine.top_100_year %></td>
        <td><%= wine.top100_rank %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @wine.id %>
</p>

<p>
  <strong>Winery full:</strong>
  <%= @wine.winery_full %>
</p>

<p>
  <strong>Wine full:</strong>
  <%= @wine.wine_full %>
</p>

<p>
  <strong>Vintage:</strong>
  <%= @wine.vintage %>
</p>

<p>
  <strong>Note:</strong>
  <%= @wine.note %>
</p>

<p>
  <strong>Taster initials:</strong>
  <%= @wine.taster_initials %>
</p>

<p>
  <strong>Color:</strong>
  <%= @wine.color %>
</p>

<p>
  <strong>Country:</strong>
  <%= @wine.country %>
</p>

<p>
  <strong>Region:</strong>
  <%= @wine.region %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wine.score %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wine.price %>
</p>

<p>
  <strong>Issue date:</strong>
  <%= @wine.issue_date %>
</p>

<p>
  <strong>Top 100 year:</strong>
  <%= @wine.top_100_year %>
</p>

<p>
  <strong>Top100 rank:</strong>
  <%= @wine.top100_rank %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>